export const WATER_REPOSITORY = Symbol('WATER_REPOSITORY')
export const WATER_METER_READING_REPOSITORY = Symbol('WATER_METER_READING_REPOSITORY')
export const USER_REPOSITORY = Symbol('USER_REPOSITORY')
