export const WATER_REPOSITORY = Symbol('WATER_REPOSITORY');
export const WATER_METER_REPOSITORY = Symbol('WATER_METER_REPOSITORY');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const ANALYSIS_REPOSITORY = Symbol('ANALYSIS_REPOSITORY');
