export { Community } from './community/entities/community.ts'
export type { HolderDto } from './community/entities/holder.dto.ts'
export { Holder } from './community/entities/holder.ts'
export { Plan } from './community/entities/plan.ts'
export type { UserDto, userSchema } from './community/entities/user.dto.ts'
export { User } from './community/entities/user.ts'
export type { WaterPointDto } from './community/entities/water-point.dto.ts'
export { WaterPoint } from './community/entities/water-point.ts'
export type { WaterZoneDto } from './community/entities/water-zone.dto.ts'
export { waterZoneSchema } from './community/entities/water-zone.dto.ts'
export { WaterZone } from './community/entities/water-zone.ts'
export type { CommunityRepository } from './community/repositories/community.repository.ts'
export type { HolderRepository } from './community/repositories/holder.repository.ts'
export type { PlanRepository } from './community/repositories/plan.repository.ts'
export type { UserRepository } from './community/repositories/user.repository.ts'
export type { WaterPointRepository } from './community/repositories/water-point.repository.ts'
export type { WaterZoneRepository } from './community/repositories/water-zone.repository.ts'
export { Issue } from './issues/entities/issue.ts'
export type { IssueRepository } from './issues/repositories/issue.repository.ts'
export type { IssueRepositoryFilters } from './issues/repositories/issue.repository-filters.ts'
export { createIssueSchema } from './issues/schemas/create-issue.schema.ts'
export type { IssueSchema } from './issues/schemas/issue.schema.ts'
export { issueSchema } from './issues/schemas/issue.schema.ts'
export { Maintenance } from './maintenance/entities/maintenance.ts'
export type { MaintenanceRepository } from './maintenance/repositories/maintenance.repository.ts'
export type { CreateMaintenanceSchema } from './maintenance/schemas/create-maintenance.schema.ts'
export { createMaintenanceSchema } from './maintenance/schemas/create-maintenance.schema.ts'
export type { MaintenanceSchema } from './maintenance/schemas/maintenance.schema.ts'
export { Provider } from './providers/entities/provider.ts'
export type { ProviderRepository } from './providers/repositories/provider.repository.ts'
export type { ProviderSchema } from './providers/schemas/provider.schema.ts'
export type { AnalysisDto } from './registers/entities/analysis.dto.ts'
export { Analysis } from './registers/entities/analysis.ts'
export type { AnalysisRepository } from './registers/repositories/analysis.repository.ts'
export type { CreateAnalysisSchema } from './registers/schemas/create-analysis.schema.ts'
export { createAnalysisSchema } from './registers/schemas/create-analysis.schema.ts'
export { BasePrismaRepository } from './repositories/base.prisma-repository.ts'
export type { GetHoldersFiltersDto } from './schemas/get-holders-filters.schema'
export { getHoldersFiltersSchema } from './schemas/get-holders-filters.schema'
export type { GetWaterPointsFiltersDto } from './schemas/get-water-points-filters.schema'
export { getWaterPointsFiltersSchema } from './schemas/get-water-points-filters.schema'
export type { GetWaterZonesFiltersDto } from './schemas/get-water-zones-filters.schema'
export { getWaterZonesFiltersSchema } from './schemas/get-water-zones-filters.schema'
export {
  type GetWaterMetersFiltersDto,
  getWaterMetersFiltersSchema,
  type WaterMeterDto
} from './water-meters/entities/water-meter.dto.ts'
export { WaterMeter } from './water-meters/entities/water-meter.ts'
export type { WaterMeterReadingDto } from './water-meters/entities/water-meter-reading.dto.ts'
export { waterMeterReadingSchema } from './water-meters/entities/water-meter-reading.dto.ts'
export { WaterMeterReading } from './water-meters/entities/water-meter-reading.ts'
export type { WaterMeterRepository } from './water-meters/repositories/water-meter.repository.ts'
export type { WaterMeterReadingRepository } from './water-meters/repositories/water-meter-reading.repository.ts'
