export { Community } from './entities/community.ts'
export { Holder } from './entities/holder.ts'
export { Issue } from './entities/issue.ts'
export type { CreateIssueDto } from './entities/create-issue.dto.ts'
export type { IssueDto } from './entities/issue.dto.ts'
export { issueSchema } from './schemas/issue.schema.ts'
export { createIssueSchema } from './schemas/create-issue.schema.ts'
export type { IssueSchema } from './schemas/issue.schema.ts'
export { Plan } from './entities/plan.ts'
export { WaterMeter } from './entities/water-meter.ts'
export { WaterMeterReading } from './entities/water-meter-reading.ts'
export { WaterPoint } from './entities/water-point.ts'
export { BasePrismaRepository } from './repositories/base.prisma-repository.ts'
export type { CommunityRepository } from './repositories/community.repository.ts'
export type { HolderRepository } from './repositories/holder.repository.ts'
export type { PlanRepository } from './repositories/plan.repository.ts'
export type { WaterMeterRepository } from './repositories/water-meter.repository.ts'
export type { WaterMeterReadingRepository } from './repositories/water-meter-reading.repository.ts'
export type { WaterPointRepository } from './repositories/water-point.repository.ts'
export type { UserRepository } from './repositories/user.repository.ts'
