name: Biome CI

on: [push, pull_request]

jobs:
  biome-check:
    name: Biome Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 2.2.2

      - name: Run Biome CI (errors only)
        run: biome ci --diagnostic-level=error .